version: '2'
services:
    dreamjournal-app:
        image: dreamjournal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dreamjournal-postgresql:5432/dreamJournal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dreamjournal-elasticsearch:9300
        ports:
            - 8080:8080
    dreamjournal-postgresql:
        extends:
            file: postgresql.yml
            service: dreamjournal-postgresql
    dreamjournal-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dreamjournal-elasticsearch
